name = "realrate"
main = "src/index.js"
compatibility_date = "2024-08-01"

[vars]
DEFAULT_USD_TOMAN = ""
DEFAULT_GOLD_USD = "2450"

[[kv_namespaces]]
binding = "REALRATE_KV"
id = "4c1bbe085e964f2a8d3eb82a17befde8"
